name: Code Test

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Dependance
      uses: php-actions/composer@v6 

    - name: PHPUnit 
      uses: php-actions/phpunit@v3
    